package com.anpahn.staffguard.model;
public enum SecurityEventType {
    LOGIN_ATTEMPT, NEW_IP, VERIFICATION_CREATED, VERIFICATION_APPROVED, VERIFICATION_DENIED,
    VERIFICATION_EXPIRED, TEMPBAN_CREATED, TEMPBAN_REMOVED, TRUSTED_IP_ADDED, TRUSTED_IP_REMOVED,
    AUTH_FAILURE, RATE_LIMIT, LOCKDOWN_ENABLED, LOCKDOWN_DISABLED, ADMIN_ACTION
}
